# Generated by Django 2.1.7 on 2019-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Bok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='Shop_Bok.Book')),
            ],
        ),
    ]
